class Goods(var weight: Int, var time: Int, val name: String,val isEatable: Boolean = false)

val apple = Goods(100, 15, "Apples", true)
val milk = Goods(200, 30, "Milk", true)
val bread = Goods(100, 5, "Bread", true)
val meat = Goods(200, 10, "Meat", true)
val table = Goods(300, 30, "Table")
val chair = Goods(200, 30, "Chair")
val computer = Goods(200, 30, "Computer")
val wardrobe = Goods(600, 50, "Wardrobe")
val door = Goods(400, 40, "Door")
val lamp = Goods(300, 30, "Lamp")
val laptop = Goods(100, 30, "Laptop")
val sink = Goods(200, 30, "Sink")
val armchair = Goods(100, 30, "Armchair")
val window = Goods(300, 30, "Window")
val tv = Goods(200, 30, "TV")

val edibleProducts = mutableListOf(apple, milk, bread, meat)
val notEdibleProducts =
    mutableListOf(table, chair, computer, wardrobe, door, lamp, laptop, sink, armchair, window, tv)